### ISSUE TITLE
Update Curriculae

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/Backend#1]
"Am besten wäre es wenn ihr einfach den aktuellen Stuedienplan:

https://www.in.tum.de/fuer-studierende/bachelor-studiengaenge/informatik/studienplan/studienbeginn-ab-ws-201617.html

in Eure API:

https://tumcabe.in.tum.de/Api/curricula

hinzufügen könntet.

Der Link von WS 12/13 wurde glaube ich umbenannt auf:

https://www.in.tum.de/fuer-studierende/bachelor-studiengaenge/informatik/studienplan/studienbeginn-ab-ws-20122013-bis-sommersemester-2016.html"

Related ticket: http://tca.exgen.io/scp/tickets.php?id=187

**Comment by mammuth** [comment]
Also, how about adding other disciplinces like eg electircal engineering? (http://tca.exgen.io/scp/tickets.php?id=197)

**Comment by kordianbruck** [comment]
Hab den Studienplan hinzugefügt. @mammuth sofern da noch was im Ticket zu tun wäre, wäre geil wenn du das fertig bzw. dann zu machst.

Was wären die Links für EE? Das?
https://www.ei.tum.de/de/studium/bachelor-ei-bsei/modulbeschreibungen-bsei/

**Comment by mammuth** [comment]
Wrote an answer in the support ticket ✅ 

Let's don't add the EE curriculae for now.
