### ISSUE TITLE
MPI Fachschafts News

### ISSUE THREAD

**Issue by tgymnich** [TCA-Team/Backend#3]
Implement MPI News Feed
@kordianbruck

**Comment by TG908** [comment]
https://github.com/TCA-Team/iOS/issues/43

**Comment by kordianbruck** [comment]
On it: https://github.com/TCA-Team/TumCampusApp/issues/442

**Comment by kordianbruck** [comment]
Added: https://tumcabe.in.tum.de/Api/news/sources/
ID 15
