### ISSUE TITLE
API methods

### ISSUE THREAD

**Issue by i-walker** [TCA-Team/Backend#7]
## Proposal for API methods
- [ ]  [#1264, #491 #1225 seem like one basic GET.](https://github.com/TUM-Dev/Campus-Android/issues/1264) We can request them with ?name = "" and ?address = "". Internally, we should use a LIKE (Postgres) operator for address Strings.

- [ ] In addition to the latter. Two nice GET meth. would be a simple Boolean response for an open specified location. with ?time =  t::TIMESTAMP
```kotlin
/** @param loc = User.aroundUser() would be called by the client if no location is specified
*    @param time = now() is also called from client // we may change that I am not sure which is faster right now
/
fun locationIsOpen(loc:Location, time:TIME= now()): Boolean

fun IsOpen(time:Time= now()): Collection<Location>() 
// I don't even care if we  use a HashMap :)
if you're familiar with Higher Kinded Types we can use a Kinds<Container, Location> 
```

- [ ] [Can be messy, but I found an almost easy solution.](https://github.com/TUM-Dev/Campus-Android/issues/678) We Pattern Match over the search string and output max. 3 columns with the highest resemblance. 

- [ ] One PUT/ POST for the Crawler without specifying the Id  

- [ ] One PATCH for Users and the Crawler

- [ ]  Feature Issue: Users can Up/Down Vote the correctness of opening hours so we can debug 

- [ ] Feature Issue: Users can suggest not indexed Locations (only TUM) specifying a name and address

### missing information
- [ ] Straubing facilities 
- [ ] Weihnstephen lib
- [ ] Barrierefreiheit info's
- [ ] Ansprechparter of other facilities than IT

I am open for suggestions.

**Comment by kordianbruck** [comment]
I guess if we ever come back to this feature, we can reopen this bug.
